import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { colors, typography, spacing, shadows } from '../../theme';
import { PRHeader } from '../../components/ui/PRHeader';
import { ScreenContainer } from '../../components/ui/ScreenContainer';
import { fetchExplainabilityTrace } from '../../api/explainability';

export const GlassBoxScreen: React.FC<{ navigation: any }> = ({ navigation }) => {
  const [trace, setTrace] = useState<any>(null);

  useEffect(() => {
    fetchExplainabilityTrace().then(res => setTrace(res.data));
  }, []);

  const steps = trace?.steps || [
    { step: 1, title: 'Real-time Telemetry Ingestion', detail: 'Sensors detected Curry Road platform saturation reaching 94% with 480 incoming pax/min.' },
    { step: 2, title: 'Multi-Horizon Prediction', detail: 'Residual model projected critical threshold breach (>104%) within 45 minutes.' },
    { step: 3, title: 'Network Flow Optimization', detail: 'Evaluated 4 alternative buffer corridors. Thane suburban hub showed lowest spillover risk (4.8 pts).' },
    { step: 4, title: 'Multi-Objective Trade-off', detail: 'Dosage set to 18% to maximize bottleneck relief (-18.4 pts) while keeping travel time increase under 8 min.' }
  ];

  const features = trace?.features_importance || [
    { feature: 'Station Platform Density', weight: '38%' },
    { feature: 'Inbound Rail Schedule (Central Mainline)', weight: '27%' },
    { feature: 'Weather & Precipitation Factor', weight: '19%' },
    { feature: 'Surrounding Road Closures', weight: '16%' }
  ];

  return (
    <View style={styles.container}>
      <PRHeader
        title="Glass Box Explainability"
        subtitle="Auditable 4-Step Algorithmic Reasoning Chain"
        showBack={true}
        onBack={() => navigation.goBack()}
      />

      <ScreenContainer>
        {/* Transparency Banner */}
        <View style={[styles.banner, shadows.subtle]}>
          <Text style={styles.bannerTitle}>🛡️ No Black-Box AI Guarantee</Text>
          <Text style={styles.bannerText}>
            Every operational recommendation generated by PRAVAAH includes deterministic mathematical traces and factor weight disclosures for decision audits.
          </Text>
        </View>

        {/* 4-Step Reasoning Chain */}
        <View style={styles.section}>
          <Text style={styles.sectionHeader}>DECISION REASONING TRACE</Text>
          <View style={styles.stepList}>
            {steps.map((s: any) => (
              <View key={s.step} style={[styles.stepCard, shadows.subtle]}>
                <View style={styles.stepHeader}>
                  <View style={styles.stepBadge}>
                    <Text style={styles.stepBadgeText}>STAGE {s.step}</Text>
                  </View>
                  <Text style={styles.stepTitle}>{s.title}</Text>
                </View>
                <Text style={styles.stepDetail}>{s.detail}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Feature Importance */}
        <View style={styles.section}>
          <Text style={styles.sectionHeader}>FEATURE WEIGHT CONTRIBUTIONS</Text>
          <View style={[styles.card, shadows.subtle]}>
            {features.map((f: any, idx: number) => (
              <View
                key={idx}
                style={[
                  styles.featureRow,
                  idx !== features.length - 1 && styles.featureRowBorder,
                ]}
              >
                <Text style={styles.featureName}>{f.feature}</Text>
                <Text style={styles.featureWeight}>{f.weight}</Text>
              </View>
            ))}
          </View>
        </View>
      </ScreenContainer>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  banner: {
    backgroundColor: colors.tealSoft,
    borderColor: colors.teal,
    borderWidth: 1,
    borderRadius: spacing.radius.md,
    padding: spacing.md,
    gap: 4,
    marginBottom: spacing.md,
  },
  bannerTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.tealDark,
  },
  bannerText: {
    fontSize: 13,
    color: colors.textPrimary,
    lineHeight: 18,
  },
  section: {
    marginBottom: spacing.lg,
    gap: spacing.xs,
  },
  sectionHeader: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.textMuted,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  stepList: {
    gap: spacing.xs,
  },
  stepCard: {
    backgroundColor: colors.surface,
    borderRadius: spacing.radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 4,
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  stepBadge: {
    backgroundColor: colors.navy,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: spacing.radius.xs,
  },
  stepBadgeText: {
    color: colors.textWhite,
    fontSize: 10,
    fontWeight: '800',
  },
  stepTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    flex: 1,
  },
  stepDetail: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
    marginTop: 2,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: spacing.radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  featureRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  featureRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  featureName: {
    fontSize: 13,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  featureWeight: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.navy,
  },
});
