"""
PRAVAAH Explainability & Decision Audit Engine
Phase 10 — Plain-Language Reasoning Chains, Decision Lineage, Audit Trail, and Trust Layer
"""

import time
import logging
from typing import Dict, List, Any, Optional

from config import Config
from models.explainability import TraceStage, DecisionExplanation, AuditEvent
from services.pressure_service import calculate_pressure_index, get_pressure_level, get_pressure_color
from services.prediction_service import get_predictor
from services.network_service import get_network
from services.simulator import get_simulator
from services.intervention_service import get_intervention_engine
from services.scenario_service import get_scenario_engine

logger = logging.getLogger('pravaah.explainability')

# Standard assumptions & limitations disclosures
STANDARD_ASSUMPTIONS = [
    "Visitor demand and crowd movements are generated by the deterministic PRAVAAH simulation engine.",
    "Suburban transit platform capacities are configured prototype design parameters.",
    "Roadway and walking travel times are modeled geographic estimates.",
    "Forecast projections assume current event conditions and corridor availability persist."
]

STANDARD_LIMITATIONS = [
    "This prototype does not ingest live GPS or proprietary real-time sensor streams.",
    "Recommendations represent counterfactually simulated operational decision-support.",
    "Physical deployment requires integration with local municipal safety and transit authorities."
]

STANDARD_DATA_SOURCES = [
    "Aggregated synthetic city simulation telemetry (Phase 5)",
    "Topological transit network graph & capacity constraints (Phase 6)",
    "LightGBM residual prediction model pravaah-prediction-v1 (Phase 7)",
    "Counterfactual multi-candidate impact simulator (Phase 8)"
]

class ExplainabilityEngine:
    """
    Provides transparent, verifiable, and plain-language explanations for all PRAVAAH decisions.
    """
    def __init__(self):
        self.audit_log: List[AuditEvent] = []
        self.explanations_cache: Dict[str, DecisionExplanation] = {}
        self._init_default_audit_trail()

    def _init_default_audit_trail(self):
        """Initializes session audit trail with baseline lifecycle events."""
        self.record_audit_event(
            event_type='PREDICTION_CREATED',
            decision_id='PRV-PRED-CURRY-ROAD-1800',
            parent_decision_id=None,
            summary='Multi-horizon pressure forecast generated for 11 Mumbai zones.',
            reason='Simulated arrival velocity and platform saturation indicates critical peak at Curry Road.',
            versions={'prediction': 'v1', 'network': 1, 'scenario': 0}
        )
        self.record_audit_event(
            event_type='ACTION_RECOMMENDED',
            decision_id='PRV-ACT-REDIRECT-CURRY-ROAD-THANE-18',
            parent_decision_id='PRV-PRED-CURRY-ROAD-1800',
            summary='Recommended redirecting 18% of incoming visitors from Curry Road toward Thane.',
            reason='Optimal balance of target pressure reduction (-18 pts) and available buffer capacity.',
            versions={'prediction': 'v1', 'network': 1, 'scenario': 0}
        )

    def _reset_seed_events(self):
        """Clears the audit log and reinitializes with seed events for demo reset."""
        self.audit_log.clear()
        self.explanations_cache.clear()
        self._init_default_audit_trail()

    def record_audit_event(
        self,
        event_type: str,
        decision_id: str,
        parent_decision_id: Optional[str],
        summary: str,
        reason: str,
        versions: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> AuditEvent:
        """Records an immutable timestamped event in the decision audit trail."""
        sim = get_simulator()
        sim_state = sim.get_state()
        sim_time = sim_state.get("simulation_time", "18:00")
        
        event_id = f"EVT-{int(time.time()*1000)%100000:05d}"
        ev = AuditEvent(
            event_id=event_id,
            decision_id=decision_id,
            parent_decision_id=parent_decision_id,
            event_type=event_type,
            simulation_time=sim_time,
            timestamp=time.strftime('%Y-%m-%d %H:%M:%S'),
            summary=summary,
            reason=reason,
            versions=versions or {'prediction': 'v1', 'network': 1, 'scenario': 0},
            metadata=metadata or {}
        )
        self.audit_log.append(ev)
        # Keep last 100 events
        if len(self.audit_log) > 100:
            self.audit_log.pop(0)
        return ev

    def explain_prediction(self, zone_id: str = 'curry-road') -> DecisionExplanation:
        """Generates comprehensive Glass Box explanation for a zone forecast."""
        predictor = get_predictor()
        preds = predictor.predict_all_zones()
        zone_data = next((z for z in preds.get("zones", []) if z["zone_id"] == zone_id), preds["zones"][0])
        
        current_p = zone_data["current_pressure"]
        pred_120 = zone_data["predictions"][2]["predicted_pressure"]
        time_to_peak = zone_data.get("time_to_peak", "~2h 45m")
        drivers = zone_data.get("drivers", [])
        
        decision_id = f"PRV-PRED-{zone_id.upper()}-1800"
        
        trace = [
            TraceStage(
                stage='CURRENT_STATE',
                title='Observed Telemetry',
                message=f"{zone_data['name']} is currently operating at {current_p}/100 ({zone_data['current_level']})."
            ),
            TraceStage(
                stage='SIGNALS',
                title='Ingress Velocity',
                message='Arrival volume is exceeding local platform clearance throughput by 22%.'
            ),
            TraceStage(
                stage='NETWORK_EFFECT',
                title='Corridor Saturation',
                message='Central Mainline rail access corridors are tightening with limited pedestrian egress.'
            ),
            TraceStage(
                stage='FORECAST',
                title='Projected Peak',
                message=f"Pressure is forecast to escalate to {pred_120}/100 within {time_to_peak} without intervention."
            )
        ]
        
        explanation = DecisionExplanation(
            decision_id=decision_id,
            type='PREDICTION',
            summary=f"{zone_data['name']} is forecast to reach {pred_120}/100 within {time_to_peak}.",
            what=f"Projected crowd pressure increase from {current_p} to {pred_120} (/100).",
            why=drivers,
            network_effect=[
                "Inbound pedestrian flow concentrated on narrow station egress alleys.",
                "Radial queue buildup radiating from Lalbaugcha Raja darshan perimeter."
            ],
            impact={
                'current_pressure': current_p,
                'forecast_pressure_120m': pred_120,
                'delta': pred_120 - current_p,
                'peak_window': time_to_peak
            },
            confidence={
                'score': 0.87,
                'label': 'HIGH CONFIDENCE',
                'reason': 'Consistent multi-step simulation trajectory and verified topological corridor throughput.'
            },
            assumptions=STANDARD_ASSUMPTIONS,
            limitations=STANDARD_LIMITATIONS,
            data_sources=STANDARD_DATA_SOURCES,
            timestamp=preds.get("forecast_time", "18:00"),
            versions={'prediction': predictor.model_version, 'network': preds.get("network_version", 1)},
            trace=trace,
            technical_context={
                'model_name': 'PRAVAAH Prediction Engine v1',
                'model_type': 'Physics Baseline + LightGBM Residual Regressor',
                'validation_mae': 1.026,
                'validation_rmse': 1.274,
                'feature_signals': ['density_ratio', 'net_inflow_velocity', 'station_saturation', 'neighbor_spillover']
            }
        )
        return explanation

    def explain_intervention(self, action_id: str = 'act-redirect-curry-road-thane-18') -> DecisionExplanation:
        """Generates comprehensive Glass Box explanation for a recommended intervention."""
        engine = get_intervention_engine()
        recs = engine.get_recommendations()
        
        rec_act = recs.get("recommended_action", {})
        impact = recs.get("impact", {})
        why_list = recs.get("why_this_action", [])
        alternatives = recs.get("alternatives", [])
        
        decision_id = f"PRV-ACT-{rec_act.get('source', 'curry-road').upper()}-{rec_act.get('destination', 'thane').upper()}-{rec_act.get('dosage_pct', 18)}"
        
        trace = [
            TraceStage(
                stage='CURRENT_STATE',
                title='Target Risk Identified',
                message=f"{rec_act.get('source_name', 'Curry Road')} forecast to exceed safe operating limits ({impact.get('target_pressure_before', 94)}/100)."
            ),
            TraceStage(
                stage='CANDIDATE_ACTIONS',
                title='Alternative Search',
                message='Evaluated 25 destination and dosage candidates across available network corridors.'
            ),
            TraceStage(
                stage='CONSTRAINT_CHECK',
                title='Safety & Route Validation',
                message='Eliminated candidates with saturated destination buffers or closed transit edges.'
            ),
            TraceStage(
                stage='COUNTERFACTUAL',
                title='Impact Simulation',
                message=f"Redirecting {rec_act.get('dosage_pct', 18)}% toward {rec_act.get('destination_name', 'Thane')} reduces target pressure by {impact.get('pressure_reduction', 18)} pts."
            ),
            TraceStage(
                stage='DECISION',
                title='Optimal Action Selected',
                message='Selected 18% redirection: best balance of pressure reduction, route capacity, and minimal side effect (+8 pts).'
            )
        ]
        
        explanation = DecisionExplanation(
            decision_id=decision_id,
            type='INTERVENTION',
            summary=f"PRAVAAH recommends redirecting {rec_act.get('dosage_pct', 18)}% of incoming visitors from {rec_act.get('source_name', 'Curry Road')} toward {rec_act.get('destination_name', 'Thane')}.",
            what=f"Redirect {rec_act.get('dosage_pct', 18)}% incoming flow toward suburban buffer capacity.",
            why=why_list,
            network_effect=[
                f"Transfers approximately ~{impact.get('affected_people', 2500):,} visitors/hour away from congested Central corridor.",
                f"Leverages operational suburban rail connections toward {rec_act.get('destination_name', 'Thane')}."
            ],
            impact={
                'target_before': impact.get('target_pressure_before', 94),
                'target_after': impact.get('target_pressure_after', 76),
                'reduction': impact.get('pressure_reduction', 18),
                'destination_before': impact.get('destination_pressure_before', 54),
                'destination_after': impact.get('destination_pressure_after', 62),
                'side_effect': impact.get('side_effect_increase', 8),
                'critical_zones_before': impact.get('critical_zones_before', 3),
                'critical_zones_after': impact.get('critical_zones_after', 1)
            },
            confidence={
                'score': rec_act.get('confidence', 0.87),
                'label': rec_act.get('confidence_label', 'HIGH CONFIDENCE'),
                'reason': 'Tested across counterfactual simulation with verified spare buffer capacity.'
            },
            assumptions=STANDARD_ASSUMPTIONS,
            limitations=STANDARD_LIMITATIONS,
            data_sources=STANDARD_DATA_SOURCES,
            timestamp=recs.get("created_at", "18:00"),
            versions={'network': recs.get("network_version", 1), 'recommendation': recs.get("recommendation_id", "rec-1")},
            trace=trace,
            technical_context={
                'selected_action_score': rec_act.get('score', 0.91),
                'candidate_evaluations': alternatives,
                'rejected_candidates_count': recs.get('rejections_evaluated', 6),
                'weights': {
                    'pressure_reduction': 1.0,
                    'side_effect_penalty': 0.8,
                    'capacity_penalty': 0.9,
                    'travel_time_penalty': 0.4
                }
            }
        )
        return explanation

    def get_audit_trail(self, event_type: Optional[str] = None) -> List[Dict[str, Any]]:
        """Returns chronological list of decision audit log events."""
        events = self.audit_log
        if event_type and event_type != 'ALL':
            events = [e for e in events if e.event_type == event_type]
            
        return [
            {
                'event_id': e.event_id,
                'decision_id': e.decision_id,
                'parent_decision_id': e.parent_decision_id,
                'event_type': e.event_type,
                'simulation_time': e.simulation_time,
                'timestamp': e.timestamp,
                'summary': e.summary,
                'reason': e.reason,
                'versions': e.versions
            }
            for e in reversed(events)
        ]

# Global Singleton Explainability Engine Instance
_global_explainability_engine: Optional[ExplainabilityEngine] = None

def get_explainability_engine() -> ExplainabilityEngine:
    global _global_explainability_engine
    if _global_explainability_engine is None:
        _global_explainability_engine = ExplainabilityEngine()
    return _global_explainability_engine
